# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mscape_test_build_workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyyaml climb-onyx-client
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install code base
      run: pip install .
    - name: Install tests and linter
      run: pip install ruff pytest pytest-cov
    - name: Lint with ruff
      run: |
        # Stop the build if there are Python syntax errors
        ruff check --output-format=github --target-version=py312
        # Add error codes with "--ignore" if want to progress with allowed errors
        # e.g. ruff check --output-format=github --target-version=py312 --ignore PTH118,PTH123
    - name: Test with pytest
      run: |
        pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
